### ISSUE TITLE
Question about isFirstApplication

### ISSUE THREAD

**Issue by mingwayzhang** [rovo89/XposedBridge#107]
Hi @rovo89,

I have recently looked at the "`isFirstApplication`" and get confused. So I am wondering when this field will be "`false`"? From the comments, it says:

> Set to `true` if this is the first (and main) application for this process.

But could a process have more than one app? I may understand in an incorrect way. So I assume it means package. However, I have tried to create a sub-package for one app and use a call to invoke methods in the sub-package, but it does not make a difference when I filter the methods to be hooked using this field. Any help is appreciated. Thanks!

**Comment by rovo89** [comment]
> But could a process have more than one app?

Yes, that is possible:

> You can also set `android:process` so that components of different applications run in the same process—provided that the applications share the same Linux user ID and are signed with the same certificates.
> https://developer.android.com/guide/components/processes-and-threads.html#Processes

I think SystemUI and Keyguard are in one process since at least Lollipop. Just log all packages which have this flag set to `false` to get an idea.

And if I remember correctly, an app could also load the code of another app into its own process: https://developer.android.com/reference/android/content/Context.html#CONTEXT_INCLUDE_CODE
Which should also trigger `handleLoadPackage()`, as you might want to hook that code as well.

Java package names are completely unrelated to that.
