### ISSUE TITLE
 Recent often appear err Loading module   File does not exist

### ISSUE THREAD

**Issue by qssq666123** [rovo89/XposedBridge#145]
I use the development tool is Android studio
I compile each time to restart, but after the restart is the following error, I need to compile again to restart once
Once tired, 2 times sad

Build.gradle
  compileSdkVersion 25
    buildToolsVersion "25.0.0"
        minSdkVersion 11
        targetSdkVersion 21
   provided 'de.robv.android.xposed:api:82'
    provided 'de.robv.android.xposed:api:82:sources'

xposed framework is 27
Tool--enable intergration is disable  or enable   Still so

850 154-154/? I/Xposed: Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
12-25 20:36:28.930 154-154/? I/Xposed: -----------------
                                       2016年12月25日 下午12:36:28 UTC
                                       Loading Xposed v54 (for Zygote)...
12-25 20:36:28.930 154-154/? I/Xposed: Running ROM 'samsung-userdebug 4.4.2 KOT49H 3.7.5.1117 test-keys' with fingerprint 'Android/samsung/samsung:4.4.2/KOT49H/3.7.5.1117:userdebug/test-keys'
12-25 20:36:28.940 154-154/? I/Xposed: Loading modules from /data/app/cn.qssq666.pro.redpackaget-1.apk
12-25 20:36:28.940 154-154/? I/Xposed:   File does not exist
12-25 20:36:28.940 154-154/? I/Xposed: Loading modules from /data

**Comment by aviraxp** [comment]
What's the meaning?

It seems that Xposed failed to load modules because the module does not exist. Xposed use an modules.list to load modules, then I assume that the broadcast to Xposed Installer failed because of some reasons. Please try to re-click the module in Xposed Installer after installation.

**Comment by qssq666123** [comment]
Yes, I'm going to restart two times now.

**Comment by qssq666123** [comment]
Reinstall the plugin or module? I need to restart after running failed to find the success of loading so I compile again before loading  lug in can actually be open ,is not a gradle problem?

**Comment by aviraxp** [comment]
Your problem is related to this:

In Android 4.4, The first time you install an apk, it will be installed like /data/app/xxx-1.apk
The second time, xxx-2.apk,
The third time, xxx-1.apk.......

So just the Xposed Installer failed to update modules.list because of some reasons, maybe you use some apps that prevent it from receiving broadcasts that the app is re-installed.

So, check about what I mentioned, and re-click the modules in Xposed Installer after you re-installed to make sure.

**Comment by qssq666123** [comment]
Are you Chinese? If yes, can you speak Chinese? My English is Baidu translate
Reinstall? Do you want to re check the module management interface?

**Comment by qssq666123** [comment]
into the plug-in manager to re check and restart really useful does not need but after all trouble if you can do a app or a shell command just fine

**Comment by rovo89** [comment]
I see two reasons why this might happen:
1. You are not waiting long enough after installing the new version. It might take a few seconds until the intent reaches Xposed Installer. You will see a toast message once the module list has been updated.
2. You have installed something that blocks the app from receiving the "package updated" intent.

**Comment by qssq666123** [comment]
Yeah, I'm more irritable may notice bar did not prompt when I directly restart really need a few seconds to prompt
