### ISSUE TITLE
Cannot modify static variables of class

### ISSUE THREAD

**Issue by seven-tan** [rovo89/XposedBridge#163]
![image](https://cloud.githubusercontent.com/assets/20498738/23899031/7dac2c06-08ee-11e7-9686-f9e9d72d8370.png)
When the handleLoadPackage method is called for the first time I will get false/true, the next few calls I will get true/true, but every time I call to get false/true, why?

**Comment by liudongmiao** [comment]
You don't understand `static` in Java, please refer to java's tutorial.

**Comment by rovo89** [comment]
The real problem here is that the calls to `handleLoadPackage()` are usually executed in different processes. If you change the variable in process A, it won't be changed in process B. There are just a few apps/services which share a process, which explains why you sometimes do see the change in the next call.

**Comment by seven-tan** [comment]
Thanks for your quick reply !
I know the reason, class Main is created in process  zygote, others process forker from zygote and change the variable in this process
