### ISSUE TITLE
Public interface

### ISSUE THREAD

**Issue by daimoniuma** [rovo89/XposedBridge#184]
Is there possibility to findAndHook all ActionMode.Callback presented in any app without creating special hooks per app. startSupportActionMode & startActionMode not always used.

**Comment by rovo89** [comment]
You can't hook method **definitions** in interfaces (nor abstract methods), only method **implemenations** (i.e. everything that has a method body). So you would have to find a list of all classes implementing this interface. I don't think there's a Java API for that. Alternatively, choose a different approach, e.g. hook the place where these instances are used.

**Comment by daimoniuma** [comment]
I know that I can't hook all this, but I can't understand, is it impossible to enlarge API with some tricks? I disappeared why interfaces cannot be hooked. 😒

**Comment by rovo89** [comment]
I don't see a way to do this. In Java (or at least in the ART implementation of it), each method implementation is an object, and classes that have this method just keep a reference to it. A subclass will have a reference to the exact same method object, unless it overrides the method with its own implementation. Put simply, Xposed exchanges the entrypoints stored in the method object. There is no object for the method definition itself though. Each class implementing that interface will do so with its own method implementation. Therefore hooking a method from an interface requires finding all classes that implement it (directly or indirectly). I don't think Java reflection (which most Xposed helper methods build upon) offers any way to do that. It would probably require checking all classes every loaded, and I don't think there's an API for that either. And even that would be incomplete, further classes which aren't even loaded yet wouldn't be caught by this. You know, hardly anything is "impossible" in the IT world, but this would get way too complicated. Besides that, if you're trying to hook something with a "wildcard" filter, you might end up hooking something you didn't want to hook. So that's probably not the right way to do it.

**Comment by embedSky** [comment]
发自网易邮箱大师


On 9/1/2017 22:56，daimoniuma<notifications@github.com> wrote：

I know that I can't hook all this, but I can't understand, is it impossible to enlarge API with some tricks? I disappeared why interfaces cannot be hooked. 😒
