### ISSUE TITLE
StrictModeViolation

### ISSUE THREAD

**Issue by tonyp** [rovo89/XposedBridge#47]
I got a bug report from a user with a LG G3 (D855 / 4.4.2).
He runs into a StrictModeViolation, here's the log: http://pastebin.com/RXUYx5Yu
The module works perfectly fine on other Kitkat ROMs.

At first I thought I it is related to https://github.com/rovo89/XposedBridge/issues/36 but I completely stripped down the module without any access to XSharedPreferences and it still occurs.
It's now a bare hook into `shutdownIfNoPowerLocked()` in the `com.android.server.BatteryService` class.
I call `XposedBridge.log("something")` and `return XposedBridge.invokeOriginalMethod(param.method, param.thisObject, param.args);`

He claims the StrictMode violation pops up each time he plugs in or out the usb cable. As the hooked method does get triggered on that occasion this should be the point of failure.

Would you have an idea on why this could be happening? As the only thing I call is the log I even tried to call that with a `StrictMode.allowThreadDiskWrites()`, but without success.

Thanks.

**Comment by rovo89** [comment]
All of the violations in the log are caused by Google Maps. I see no relation to Xposed here, maybe the user provided a wrong log file?

Anyway, you could try to use `Log.d()` directly, then you don't need to care about strict mode for your own code.

By the way, you'll rarely need `invokeOriginalMethod()`. Usually, you don't replace methods completely, but just execute code before/after them. Want to execute the original method only under certain circumstances? Then check these in the "before" callback and call `param.setResult(null)` in case you want to block it (for `void` methods, otherwise a valid result of course).

**Comment by tonyp** [comment]
Oh you're right, how could I miss the Maps lines in there, I'll contact him again.

Regarding `invokeOriginalMethod()`: I usually used `XC_MethodReplacement` in conjunction with `replaceHookedMethod()` and `invokeOriginalMethod()`. 

Is there an advantage of using `XC_MethodHook` and `beforeHookedMethod()`? I assumed it's basically the same thing just a different approach and doesn't really matter.

**Comment by rovo89** [comment]
Well, it goes through more steps when you replace a method. Actually, the code for replacing is built on top of before/after callbacks.

**Comment by tonyp** [comment]
Ah good too know, thanks! Then I'm going to refactor my code. 
The information and docs regarding Xposed are a bit scattered and sometimes not to easy to get a hold of. But I know how tedious maintaining something like that can be, especially considering that you know your code by heart. And of course your spare free time is clearly more valuable on trying to work on the many issues regarding Lollipop (and I can just study the XposedHelper class a bit more closely).
