### ISSUE TITLE
API to check if xposed framework is installed or not.

### ISSUE THREAD

**Issue by Ashish-Bansal** [rovo89/XposedBridge#83]
Hi,

Is there any API to check if xposed framework is installed or not ? 

I checked Xposed Installer code and found that it checks for "XposedBridge.jar" existence which differs for both dalvik and ART, and it might could change in future.

Thanks!

**Comment by rovo89** [comment]
I would probably check if an app with package name `de.robv.android.xposed.installer` is installed. Not sure if it's 100% future-proof, but I would say it's more reliable than checking for any files. And Xposed can't provide an API itself, because... it wouldn't be there if Xposed isn't installed. :)

If you're concerned about the actual framework not being installed (but the app is)... don't be. There are other things that could go wrong, e.g. your module might not be enabled, the user might not have rebooted yet, it might have failed to load for various reasons... My recommendation is that you add a method to your app like `isActive()`, which by default returns false. Then you hook it from your module and change it to return `true` instead.

**Comment by C3C0** [comment]
What about finding out from a stack trace using Thread.currentThread().getStackTrace() ?
